### ISSUE TITLE
Tap release as a GitHub Action

### ISSUE THREAD

**Issue by sjparkinson** [toolmantim/tap-release#86]
It'd be really neat to be able to use this Probot app as a GitHub Action, given it's so repository specific.

https://github.com/features/actions

https://probot.github.io/docs/deployment/#github-actions

**Comment by toolmantim** [comment]
I'd love to see that too! I believe we need to get master updated to be fully working with Probot v9, similar to the work @TimonVS did with the recent Release Draft PRs: https://github.com/toolmantim/release-drafter/pulls?q=is%3Apr+is%3Aclosed
